### ISSUE TITLE
您好，Bot群里@发消息不回，单独发报错

### ISSUE THREAD

**Issue by mcc1095319343** [Widecss/ChatGPT-Bot#1]
报错如下：
启动完毕~
Traceback (most recent call last):
  File "D:\Data\Fun2\qqchatgpt2-main\cqhttp.py", line 52, in loop
    await self.loop_connect(api, session)
  File "D:\Data\Fun2\qqchatgpt2-main\cqhttp.py", line 45, in loop_connect
    await self.on_handle(data, api)
  File "D:\Data\Fun2\qqchatgpt2-main\cqhttp.py", line 81, in on_handle
    message: str = cqutil.get_message_without_at_and_whitespace(data)
  File "D:\Data\Fun2\qqchatgpt2-main\cqutil.py", line 18, in get_message_without_at_and_whitespace
    return data.get("message", "").removeprefix(at_me()).strip()
AttributeError: 'str' object has no attribute 'removeprefix'
'str' object has no attribute 'removeprefix'

**Comment by Widecss** [comment]
哦抱歉，我没有考虑到在 **Python 3.9** 以下没有 **str.removeprefix()** 方法，拉取最新代码试试？

**Comment by mcc1095319343** [comment]
【与服务器通信出现异常，请重试：Error communicating with OpenAI】好像也不行

**Comment by mcc1095319343** [comment]
开不开vpn都一样
但是会有消息
启动完毕~
--[User]: 你好
--[User]: 一宵冷雨 你好
--[User]: @Bot 你好

**Comment by Widecss** [comment]
这个提示是 openai 库发出的，原因可能是 aiohttp 库无法连接至 [https://api.openai.com/](https://api.openai.com/)
据我所知在某些高校的网络中，使用 aiohttp 库会出现 OpenAI API 证书问题，但是此时使用 requests 库是可以连接的

一个临时的解决方法是，打开 **api.py** 文件，将 121 行的
~~~
response = await openai.ChatCompletion.acreate(
~~~

替换为以下代码，即可切换至 requests 库
~~~
response = openai.ChatCompletion.create(
~~~

如果可以记得回来告诉我，我去更新代码

**Comment by mcc1095319343** [comment]
可以啦，感谢！！！

**Comment by mcc1095319343** [comment]
另外我想问一下，每次都会有【tokens】的累计，但是重置后会重新叠加是openai的api调用次数限制吗？是不是通过api key和模型 形式调用没有免费的？

**Comment by Widecss** [comment]
这些问题是关于 **ChatGPT** 的，你可以在 [官方文档](https://platform.openai.com/docs/introduction) 中得到答案，并且可以使用官方提供的工具 [Tokenizer](https://platform.openai.com/tokenizer) 计算某一段话包含的 token。

API 确实没有免费的，仅仅在刚注册时拥有试用金额，如果需要免费，可以尝试那种，使用 OpenAI 帐号登录来爬取个人聊天 API 的方式实现的项目。

API 调用次数没有限制，token 的限制表现在模型单次会话的长度上，即 **每次回复都会记住之前说过的话** 这件事情，并且 token 越高，消耗的价格越多，重置将 **遗忘之前说过的话**

如果本项目的问题已经解决，请关闭该 issue，谢谢。
